/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ClientRouteImport } from './routes/client'
import { Route as CollectionsRouteImport } from './routes/collections'
import { Route as LoginRouteImport } from './routes/login'
import { Route as QuotesRouteImport } from './routes/quotes'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminDiscountsRouteImport } from './routes/admin.discounts'
import { Route as AdminInventoryRouteImport } from './routes/admin.inventory'
import { Route as AdminLabelsRouteImport } from './routes/admin.labels'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminPaymentMethodsRouteImport } from './routes/admin.payment-methods'
import { Route as AdminPurchaseOrdersRouteImport } from './routes/admin.purchase-orders'
import { Route as AdminPurchasesRouteImport } from './routes/admin.purchases'
import { Route as AdminQuotesRouteImport } from './routes/admin.quotes'
import { Route as AdminShippingRouteImport } from './routes/admin.shipping'
import { Route as AdminStockRouteImport } from './routes/admin.stock'
import { Route as AdminSuppliersRouteImport } from './routes/admin.suppliers'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as ClientOrdersRouteImport } from './routes/client.orders'
import { Route as ProductQrIdRouteImport } from './routes/product.qr.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientRoute = ClientRouteImport.update({
  id: '/client',
  path: '/client',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsRoute = CollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const QuotesRoute = QuotesRouteImport.update({
  id: '/quotes',
  path: '/quotes',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDiscountsRoute = AdminDiscountsRouteImport.update({
  id: '/discounts',
  path: '/discounts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInventoryRoute = AdminInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLabelsRoute = AdminLabelsRouteImport.update({
  id: '/labels',
  path: '/labels',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentMethodsRoute = AdminPaymentMethodsRouteImport.update({
  id: '/payment-methods',
  path: '/payment-methods',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPurchaseOrdersRoute = AdminPurchaseOrdersRouteImport.update({
  id: '/purchase-orders',
  path: '/purchase-orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPurchasesRoute = AdminPurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => AdminRoute,
} as any)
const AdminQuotesRoute = AdminQuotesRouteImport.update({
  id: '/quotes',
  path: '/quotes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminShippingRoute = AdminShippingRouteImport.update({
  id: '/shipping',
  path: '/shipping',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStockRoute = AdminStockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSuppliersRoute = AdminSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const ClientOrdersRoute = ClientOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => ClientRoute,
} as any)
const ProductQrIdRoute = ProductQrIdRouteImport.update({
  id: '/product/qr/$id',
  path: '/product/qr/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/catalog': typeof CatalogRoute
  '/checkout': typeof CheckoutRoute
  '/client': typeof ClientRouteWithChildren
  '/collections': typeof CollectionsRoute
  '/login': typeof LoginRoute
  '/quotes': typeof QuotesRoute
  '/register': typeof RegisterRoute
  '/admin/discounts': typeof AdminDiscountsRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/labels': typeof AdminLabelsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payment-methods': typeof AdminPaymentMethodsRoute
  '/admin/purchase-orders': typeof AdminPurchaseOrdersRoute
  '/admin/purchases': typeof AdminPurchasesRoute
  '/admin/quotes': typeof AdminQuotesRoute
  '/admin/shipping': typeof AdminShippingRoute
  '/admin/stock': typeof AdminStockRoute
  '/admin/suppliers': typeof AdminSuppliersRoute
  '/admin/users': typeof AdminUsersRoute
  '/client/orders': typeof ClientOrdersRoute
  '/admin/': typeof AdminIndexRoute
  '/product/qr/$id': typeof ProductQrIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/catalog': typeof CatalogRoute
  '/checkout': typeof CheckoutRoute
  '/client': typeof ClientRouteWithChildren
  '/collections': typeof CollectionsRoute
  '/login': typeof LoginRoute
  '/quotes': typeof QuotesRoute
  '/register': typeof RegisterRoute
  '/admin/discounts': typeof AdminDiscountsRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/labels': typeof AdminLabelsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payment-methods': typeof AdminPaymentMethodsRoute
  '/admin/purchase-orders': typeof AdminPurchaseOrdersRoute
  '/admin/purchases': typeof AdminPurchasesRoute
  '/admin/quotes': typeof AdminQuotesRoute
  '/admin/shipping': typeof AdminShippingRoute
  '/admin/stock': typeof AdminStockRoute
  '/admin/suppliers': typeof AdminSuppliersRoute
  '/admin/users': typeof AdminUsersRoute
  '/client/orders': typeof ClientOrdersRoute
  '/admin': typeof AdminIndexRoute
  '/product/qr/$id': typeof ProductQrIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/catalog': typeof CatalogRoute
  '/checkout': typeof CheckoutRoute
  '/client': typeof ClientRouteWithChildren
  '/collections': typeof CollectionsRoute
  '/login': typeof LoginRoute
  '/quotes': typeof QuotesRoute
  '/register': typeof RegisterRoute
  '/admin/discounts': typeof AdminDiscountsRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/labels': typeof AdminLabelsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payment-methods': typeof AdminPaymentMethodsRoute
  '/admin/purchase-orders': typeof AdminPurchaseOrdersRoute
  '/admin/purchases': typeof AdminPurchasesRoute
  '/admin/quotes': typeof AdminQuotesRoute
  '/admin/shipping': typeof AdminShippingRoute
  '/admin/stock': typeof AdminStockRoute
  '/admin/suppliers': typeof AdminSuppliersRoute
  '/admin/users': typeof AdminUsersRoute
  '/client/orders': typeof ClientOrdersRoute
  '/admin/': typeof AdminIndexRoute
  '/product/qr/$id': typeof ProductQrIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/cart'
    | '/catalog'
    | '/checkout'
    | '/client'
    | '/collections'
    | '/login'
    | '/quotes'
    | '/register'
    | '/admin/discounts'
    | '/admin/inventory'
    | '/admin/labels'
    | '/admin/orders'
    | '/admin/payment-methods'
    | '/admin/purchase-orders'
    | '/admin/purchases'
    | '/admin/quotes'
    | '/admin/shipping'
    | '/admin/stock'
    | '/admin/suppliers'
    | '/admin/users'
    | '/client/orders'
    | '/admin/'
    | '/product/qr/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/catalog'
    | '/checkout'
    | '/client'
    | '/collections'
    | '/login'
    | '/quotes'
    | '/register'
    | '/admin/discounts'
    | '/admin/inventory'
    | '/admin/labels'
    | '/admin/orders'
    | '/admin/payment-methods'
    | '/admin/purchase-orders'
    | '/admin/purchases'
    | '/admin/quotes'
    | '/admin/shipping'
    | '/admin/stock'
    | '/admin/suppliers'
    | '/admin/users'
    | '/client/orders'
    | '/admin'
    | '/product/qr/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/cart'
    | '/catalog'
    | '/checkout'
    | '/client'
    | '/collections'
    | '/login'
    | '/quotes'
    | '/register'
    | '/admin/discounts'
    | '/admin/inventory'
    | '/admin/labels'
    | '/admin/orders'
    | '/admin/payment-methods'
    | '/admin/purchase-orders'
    | '/admin/purchases'
    | '/admin/quotes'
    | '/admin/shipping'
    | '/admin/stock'
    | '/admin/suppliers'
    | '/admin/users'
    | '/client/orders'
    | '/admin/'
    | '/product/qr/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CartRoute: typeof CartRoute
  CatalogRoute: typeof CatalogRoute
  CheckoutRoute: typeof CheckoutRoute
  ClientRoute: typeof ClientRouteWithChildren
  CollectionsRoute: typeof CollectionsRoute
  LoginRoute: typeof LoginRoute
  QuotesRoute: typeof QuotesRoute
  RegisterRoute: typeof RegisterRoute
  ProductQrIdRoute: typeof ProductQrIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client': {
      id: '/client'
      path: '/client'
      fullPath: '/client'
      preLoaderRoute: typeof ClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections': {
      id: '/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quotes': {
      id: '/quotes'
      path: '/quotes'
      fullPath: '/quotes'
      preLoaderRoute: typeof QuotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/discounts': {
      id: '/admin/discounts'
      path: '/discounts'
      fullPath: '/admin/discounts'
      preLoaderRoute: typeof AdminDiscountsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inventory': {
      id: '/admin/inventory'
      path: '/inventory'
      fullPath: '/admin/inventory'
      preLoaderRoute: typeof AdminInventoryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/labels': {
      id: '/admin/labels'
      path: '/labels'
      fullPath: '/admin/labels'
      preLoaderRoute: typeof AdminLabelsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payment-methods': {
      id: '/admin/payment-methods'
      path: '/payment-methods'
      fullPath: '/admin/payment-methods'
      preLoaderRoute: typeof AdminPaymentMethodsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/purchase-orders': {
      id: '/admin/purchase-orders'
      path: '/purchase-orders'
      fullPath: '/admin/purchase-orders'
      preLoaderRoute: typeof AdminPurchaseOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/purchases': {
      id: '/admin/purchases'
      path: '/purchases'
      fullPath: '/admin/purchases'
      preLoaderRoute: typeof AdminPurchasesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/quotes': {
      id: '/admin/quotes'
      path: '/quotes'
      fullPath: '/admin/quotes'
      preLoaderRoute: typeof AdminQuotesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/shipping': {
      id: '/admin/shipping'
      path: '/shipping'
      fullPath: '/admin/shipping'
      preLoaderRoute: typeof AdminShippingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/stock': {
      id: '/admin/stock'
      path: '/stock'
      fullPath: '/admin/stock'
      preLoaderRoute: typeof AdminStockRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/suppliers': {
      id: '/admin/suppliers'
      path: '/suppliers'
      fullPath: '/admin/suppliers'
      preLoaderRoute: typeof AdminSuppliersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/client/orders': {
      id: '/client/orders'
      path: '/orders'
      fullPath: '/client/orders'
      preLoaderRoute: typeof ClientOrdersRouteImport
      parentRoute: typeof ClientRoute
    }
    '/product/qr/$id': {
      id: '/product/qr/$id'
      path: '/product/qr/$id'
      fullPath: '/product/qr/$id'
      preLoaderRoute: typeof ProductQrIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminDiscountsRoute: typeof AdminDiscountsRoute
  AdminInventoryRoute: typeof AdminInventoryRoute
  AdminLabelsRoute: typeof AdminLabelsRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminPaymentMethodsRoute: typeof AdminPaymentMethodsRoute
  AdminPurchaseOrdersRoute: typeof AdminPurchaseOrdersRoute
  AdminPurchasesRoute: typeof AdminPurchasesRoute
  AdminQuotesRoute: typeof AdminQuotesRoute
  AdminShippingRoute: typeof AdminShippingRoute
  AdminStockRoute: typeof AdminStockRoute
  AdminSuppliersRoute: typeof AdminSuppliersRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDiscountsRoute: AdminDiscountsRoute,
  AdminInventoryRoute: AdminInventoryRoute,
  AdminLabelsRoute: AdminLabelsRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminPaymentMethodsRoute: AdminPaymentMethodsRoute,
  AdminPurchaseOrdersRoute: AdminPurchaseOrdersRoute,
  AdminPurchasesRoute: AdminPurchasesRoute,
  AdminQuotesRoute: AdminQuotesRoute,
  AdminShippingRoute: AdminShippingRoute,
  AdminStockRoute: AdminStockRoute,
  AdminSuppliersRoute: AdminSuppliersRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ClientRouteChildren {
  ClientOrdersRoute: typeof ClientOrdersRoute
}

const ClientRouteChildren: ClientRouteChildren = {
  ClientOrdersRoute: ClientOrdersRoute,
}

const ClientRouteWithChildren =
  ClientRoute._addFileChildren(ClientRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CartRoute: CartRoute,
  CatalogRoute: CatalogRoute,
  CheckoutRoute: CheckoutRoute,
  ClientRoute: ClientRouteWithChildren,
  CollectionsRoute: CollectionsRoute,
  LoginRoute: LoginRoute,
  QuotesRoute: QuotesRoute,
  RegisterRoute: RegisterRoute,
  ProductQrIdRoute: ProductQrIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
